name: Build binary
on: push

jobs:
  build_job:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} / ${{ matrix.arch }}

    # Run steps on a matrix of arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: bullseye
          - arch: armv7
            distro: bullseye
          - arch: armv6
            distro: bullseye
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}
          # The shell to use inside the container
          shell: /bin/sh

          # Setup dependencies
          install: |
            apt-get update -q -y
            apt-get install -q -y python3 python3-pip
            pip install poetry

          run: |
            uname -a
            python --version
            pip --version
            poetry --version

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts"
